import assert from 'node:assert/strict';
const listeners=new Map(),queue=[];
const canvas={style:{},classList:{add(){},remove(){}},setAttribute(){},addEventListener(type,fn){listeners.set(type,fn);},setPointerCapture(){},getContext(type){return type==='2d'?new Proxy({},{get:()=>()=>{}}):null;}};
globalThis.document={hidden:false,createElement:()=>canvas,createElementNS:()=>canvas,addEventListener(){}};
globalThis.window={devicePixelRatio:1};globalThis.devicePixelRatio=1;
globalThis.matchMedia=q=>({matches:q.includes('reduced-motion'),addEventListener(){}});
globalThis.ResizeObserver=class {observe(){}disconnect(){}};
globalThis.requestAnimationFrame=fn=>{queue.push(fn);return queue.length;};
globalThis.cancelAnimationFrame=()=>{};
const host={dataset:{},clientWidth:390,append(){},getBoundingClientRect:()=>({width:390,height:430})};
let completed=0;
const {createBouquet}=await import('./bouquet3d.js');
const scene=createBouquet(host,()=>completed++,message=>{throw Error(message);});
assert.equal(scene.manifest.length,75);
assert.equal(scene.manifest.filter(f=>f.kind==='tulip').length,50);
assert.equal(scene.manifest.filter(f=>f.kind==='lily').length,25);
for(const sx of [-1,1])for(const sz of [-1,1])assert.ok(scene.manifest.filter(f=>f.position[0]*sx>0&&f.position[2]*sz>0).length>=15);
scene.start();queue.shift()(performance.now()+700);
assert.equal(completed,1);assert.equal(host.dataset.bloomed,'75');assert.equal(host.dataset.state,'interactive');
listeners.get('keydown')({key:'ArrowRight',preventDefault(){}});queue.shift()(performance.now()+800);
assert.ok(Number(host.dataset.yaw)>.15);
scene.start();queue.shift()(performance.now()+900);
assert.equal(completed,2);assert.equal(host.dataset.yaw,'0.1500');assert.equal(host.dataset.zoom,'1.000');
console.log('PASS: 50 tulips + 25 lilies; flowers in all four horizontal quadrants; reduced motion; keyboard rotation; replay resets camera and blooms.');
